*****************************************************************
*   THIS FILE IS GENERATED BY THE FUNCTION LIBRARY.             *
*   NEVER CHANGE IT MANUALLY, PLEASE!                           *
*****************************************************************
INCLUDE LZHCM_RFC_EMPLOYEEU01.
                    "ZHCM_EMPLOYEE_RFC
INCLUDE LZHCM_RFC_EMPLOYEEU02.
                    "ZHCM_GET_INFT_TABLES
INCLUDE LZHCM_RFC_EMPLOYEEU03.
                    "ZHCM_GET_OLDEST_DATE
INCLUDE LZHCM_RFC_EMPLOYEEU04.
                    "ZHCM_TIME_RESULTS_IN_INTERVAL
INCLUDE LZHCM_RFC_EMPLOYEEU05.
                    "ZHCM_TIME_RESULTS_VERSION_GET

